DeclareGlobalFunction("SptSetSpecSeqComponentEx");
DeclareGlobalFunction("SptSetSpecSeqModuleVectorToClass");
DeclareGlobalFunction("SptSetSpecSeqModuleClassToLeadingVector");
DeclareGlobalFunction("SptSetSpecSeqModuleExtension");